# Generated by Django 4.2.5 on 2024-07-11 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=30)),
                ('search_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cover', models.URLField()),
                ('intro', models.CharField(max_length=1000)),
                ('original_url', models.URLField()),
                ('song_id', models.CharField(max_length=200)),
                ('song_name', models.CharField(max_length=500)),
                ('song_cover', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='song',
            old_name='lyric_text',
            new_name='lyric',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='title',
            new_name='singer',
        ),
        migrations.RemoveField(
            model_name='song',
            name='url',
        ),
        migrations.AddField(
            model_name='song',
            name='original_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='singer_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='song_id',
            field=models.CharField(default=1231231312, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.URLField(),
        ),
    ]
