# Generated by Django 4.2.5 on 2024-07-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_search_singer_rename_lyric_text_song_lyric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='self_id',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
    ]
