# Generated by Django 4.2.5 on 2024-07-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_comment_options_remove_comment_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_time']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='search',
            name='keyword',
            field=models.CharField(max_length=20),
        ),
    ]
