# Generated by Django 4.2.5 on 2024-07-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_comment_options_alter_comment_create_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='song_cover',
        ),
        migrations.RemoveField(
            model_name='singer',
            name='song_id',
        ),
        migrations.RemoveField(
            model_name='singer',
            name='song_name',
        ),
    ]
